site_name: Alv67 Maker FAQ
site_description: 'Collection of FAQ for Electronic Makers'
site_author: 'Alessandro Varesi'
docs_dir: docs/
repo_name: 'alv67/maker'
repo_url: 'https://github.com/alv67/maker'
nav:
    - Home: index.md
theme:
  name: 'material'