---
# This is a workflow to compile docs to Github Pages

name: Mkdocs

# Control when the action will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  createdocu:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      -
        run: pip install mkdocs-material
      - 
        run: |
          ls -alh
          find samples-*/ -name "*.md" | cpio -pd doc/
          find samples-*/ -name "*.png" | cpio -pd doc/
          mkdocs gh-deploy --force